services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
        API_SERVER_URL: http://backend:4000
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - API_SERVER_URL=http://backend:4000
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID:-}
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=devsecret
      # Local DBs (override with env to use managed services)
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/uniun}
      - MONGO_TIMEOUT_MS=${MONGO_TIMEOUT_MS:-2000}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-neo4jpassword}
      # Optional: OpenSearch vector index
      - OPENSEARCH_HOST=${OPENSEARCH_HOST:-}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME:-}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD:-}
      - OPENSEARCH_INDEX=${OPENSEARCH_INDEX:-uniun-vectors}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - neo4j

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.3.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  mongo-data:
  neo4j-data:
